version: "3.8"

services:
  app:
    image: app
    container_name: app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./config/config.env
  db:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: myuser
    #   MONGO_INITDB_ROOT_PASSWORD: mypassword
    #   MONGO_INITDB_DATABASE: mydatabase
    env_file:
      - ./config/config.env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: